global:
  checkNewVersion: true
  sendAnonymousUsage: false

log:
  level: DEBUG

api:
  insecure: true
  dashboard: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  file:
    filename: /dynamic_conf.yml
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: docker-test_proxy
