services:
  db:
    build: ./DB
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - back_db_front
      - back_db_api
      - back_db_admin
    ports:
      - "5432:5432"
    hostname: db
  
  pgadmin:
    build:
      context: ./DB/PgAdmin
      args:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin:/pgadmin4
    networks:
      - back_db_admin
    ports:
      - "5050:80"
    hostname: pgadmin
    depends_on:
      - "db"
      
  nats:
    image: nats:2.10
    volumes:
       - ./NATS/config/:/etc/nats
    environment:
      NATS_USER: ${NATS_USER}
      NATS_PASSWORD: ${NATS_PASSWORD}
    command: "-c /etc/nats/nats.conf"
    restart: unless-stopped
    networks:
      - back_nats_api
    ports:
      - "4222:4222"
    hostname: nats

  django_api:
    build:
      context: ../
      dockerfile: ./Docker-test/API/Dockerfile
    environment:
      DJANGO_ENVIRONMENT: ${DJANGO_ENVIRONMENT}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_API_HOSTS}
      DJANGO_ORIGIN: ${DJANGO_API_ORIGIN}
      DJANGO_DB_NAME: ${POSTGRES_DB}
      DJANGO_DB_USER: ${POSTGRES_USER}
      DJANGO_DB_PASSWORD: ${POSTGRES_PASSWORD}
      DJANGO_DB_HOST: db  # This is the hostname in docker-compose
      DJANGO_DB_PORT: 5432  # Default PostgreSQL port
    volumes:
      - ../Django_api/:/app
    restart: unless-stopped
    networks:
      - back_db_api
      - back_nats_api
    ports:
      - "8020:8000"
    hostname: django_api
    depends_on:
      - "db"

  django_frontend:
    build: 
      context: ../
      dockerfile: ./Docker-test/Frontend/Django/Dockerfile
    environment:
      DJANGO_ENVIRONMENT: ${DJANGO_ENVIRONMENT}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_FRONT_HOSTS}
      DJANGO_ORIGIN: ${DJANGO_FRONT_ORIGIN}
      DJANGO_DB_NAME: ${POSTGRES_DB}
      DJANGO_DB_USER: ${POSTGRES_USER}
      DJANGO_DB_PASSWORD: ${POSTGRES_PASSWORD}
      DJANGO_DB_HOST: db  # This is the hostname in docker-compose
      DJANGO_DB_PORT: 5432  # Default PostgreSQL port
    volumes:
      - ../Django_Frontend/:/app
    restart: unless-stopped
    networks:
     - back_db_front
    ports:
      - "8010:8000"
    hostname: django_frontend
    depends_on:
     - "db"

volumes:
  db:
  pgadmin:

networks:
  back_db_front:
  back_db_api:
  back_nats_api:
  back_db_admin: