name: Docker Compose Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  compose-build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Compose services
        run: docker-compose -f Docker/docker-compose.yml build
        env:
          POSTGRES_DB: app
          POSTGRES_USER: app
          POSTGRES_PASSWORD: app
          DJANGO_ENVIRONMENT: test
          DJANGO_SUPERUSER_USERNAME: admin
          DJANGO_SUPERUSER_EMAIL: admin@admin.com
          DJANGO_SUPERUSER_PASSWORD: admin
          NATS_USER: user
          NATS_PASSWORD: password
          DOMAIN: sae.local

      - name: Start Docker Compose services
        run: docker-compose -f Docker/docker-compose.yml up -d

      - name: Install and Run Trivy vulnerability scanner
        run: |
          sudo apt-get update && sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update && sudo apt-get install trivy
          docker-compose -f Docker/docker-compose.yml config | grep 'image:' | awk '{print $2}' | while read image; do
            trivy image --exit-code 1 --ignore-unfixed $image || echo "::error ::Vulnerabilities found in $image"
          done

      - name: Check website connection
        run: |
          curl -k --retry 5 --retry-delay 5 --retry-connrefused https://${{ env.DOMAIN }} && \
          curl -k --retry 5 --retry-delay 5 --retry-connrefused https://api.${{ env.DOMAIN }}
        env:
          DOMAIN: sae.local

      - name: Scan requirements for CVEs in Django API container
        run: |
          docker-compose -f Docker/docker-compose.yml exec -T django_api /bin/bash -c "pip install safety && safety check -r /app/requirements.txt --full-report"
      
      - name: Scan requirements for CVEs in Django Frontend container
        run: |
          docker-compose -f Docker/docker-compose.yml exec -T django_frontend /bin/bash -c "pip install safety && safety check -r /app/requirements.txt --full-report"

      - name: Cleanup
        run: docker-compose -f Docker/docker-compose.yml down